
import "./globals.css";
import Header from "../components/Header";
import "../components/Header.module.css"
import ThemeProvider from "../components/ThemeProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body>
        {/* <ThemeProvider> */}
          <Header>
          </Header>
          {children}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
